module.exports = exports = [
	{value:'Kolhapur', key:'Maharashtra'},
	{value:'Port Blair', key:'Andaman & Nicobar Islands'},
	{value:'Adilabad', key:'Andhra Pradesh'},
	{value:'Adoni', key:'Andhra Pradesh'},
	{value:'Amadalavalasa', key:'Andhra Pradesh'},
	{value:'Amalapuram', key:'Andhra Pradesh'},
	{value:'Anakapalle', key:'Andhra Pradesh'},
	{value:'Anantapur', key:'Andhra Pradesh'},
	{value:'Badepalle', key:'Andhra Pradesh'},
	{value:'Banganapalle', key:'Andhra Pradesh'},
	{value:'Bapatla', key:'Andhra Pradesh'},
	{value:'Bellampalle', key:'Andhra Pradesh'},
	{value:'Bethamcherla', key:'Andhra Pradesh'},
	{value:'Bhadrachalam', key:'Andhra Pradesh'},
	{value:'Bhainsa', key:'Andhra Pradesh'},
	{value:'Bheemunipatnam', key:'Andhra Pradesh'},
	{value:'Bhimavaram', key:'Andhra Pradesh'},
	{value:'Bhongir', key:'Andhra Pradesh'},
	{value:'Bobbili', key:'Andhra Pradesh'},
	{value:'Bodhan', key:'Andhra Pradesh'},
	{value:'Chilakaluripet', key:'Andhra Pradesh'},
	{value:'Chirala', key:'Andhra Pradesh'},
	{value:'Chittoor', key:'Andhra Pradesh'},
	{value:'Cuddapah', key:'Andhra Pradesh'},
	{value:'Devarakonda', key:'Andhra Pradesh'},
	{value:'Dharmavaram', key:'Andhra Pradesh'},
	{value:'Eluru', key:'Andhra Pradesh'},
	{value:'Farooqnagar', key:'Andhra Pradesh'},
	{value:'Gadwal', key:'Andhra Pradesh'},
	{value:'Gooty', key:'Andhra Pradesh'},
	{value:'Gudivada', key:'Andhra Pradesh'},
	{value:'Gudur', key:'Andhra Pradesh'},
	{value:'Guntakal', key:'Andhra Pradesh'},
	{value:'Guntur', key:'Andhra Pradesh'},
	{value:'Hanuman Junction', key:'Andhra Pradesh'},
	{value:'Hindupur', key:'Andhra Pradesh'},
	{value:'Hyderabad', key:'Andhra Pradesh'},
	{value:'Ichchapuram', key:'Andhra Pradesh'},
	{value:'Jaggaiahpet', key:'Andhra Pradesh'},
	{value:'Jagtial', key:'Andhra Pradesh'},
	{value:'Jammalamadugu', key:'Andhra Pradesh'},
	{value:'Jangaon', key:'Andhra Pradesh'},
	{value:'Kadapa', key:'Andhra Pradesh'},
	{value:'Kadiri', key:'Andhra Pradesh'},
	{value:'Kagaznagar', key:'Andhra Pradesh'},
	{value:'Kakinada', key:'Andhra Pradesh'},
	{value:'Kalyandurg', key:'Andhra Pradesh'},
	{value:'Kamareddy', key:'Andhra Pradesh'},
	{value:'Kandukur', key:'Andhra Pradesh'},
	{value:'Karimnagar', key:'Andhra Pradesh'},
	{value:'Kavali', key:'Andhra Pradesh'},
	{value:'Khammam', key:'Andhra Pradesh'},
	{value:'Koratla', key:'Andhra Pradesh'},
	{value:'Kothagudem', key:'Andhra Pradesh'},
	{value:'Kothapeta', key:'Andhra Pradesh'},
	{value:'Kovvur', key:'Andhra Pradesh'},
	{value:'Kurnool', key:'Andhra Pradesh'},
	{value:'Kyathampalle', key:'Andhra Pradesh'},
	{value:'Macherla', key:'Andhra Pradesh'},
	{value:'Machilipatnam', key:'Andhra Pradesh'},
	{value:'Madanapalle', key:'Andhra Pradesh'},
	{value:'Mahbubnagar', key:'Andhra Pradesh'},
	{value:'Mancherial', key:'Andhra Pradesh'},
	{value:'Mandamarri', key:'Andhra Pradesh'},
	{value:'Mandapeta', key:'Andhra Pradesh'},
	{value:'Manuguru', key:'Andhra Pradesh'},
	{value:'Markapur', key:'Andhra Pradesh'},
	{value:'Medak', key:'Andhra Pradesh'},
	{value:'Miryalaguda', key:'Andhra Pradesh'},
	{value:'Mogalthur', key:'Andhra Pradesh'},
	{value:'Nagari', key:'Andhra Pradesh'},
	{value:'Nagarkurnool', key:'Andhra Pradesh'},
	{value:'Nandyal', key:'Andhra Pradesh'},
	{value:'Narasapur', key:'Andhra Pradesh'},
	{value:'Narasaraopet', key:'Andhra Pradesh'},
	{value:'Narayanpet', key:'Andhra Pradesh'},
	{value:'Narsipatnam', key:'Andhra Pradesh'},
	{value:'Nellore', key:'Andhra Pradesh'},
	{value:'Nidadavole', key:'Andhra Pradesh'},
	{value:'Nirmal', key:'Andhra Pradesh'},
	{value:'Nizamabad', key:'Andhra Pradesh'},
	{value:'Nuzvid', key:'Andhra Pradesh'},
	{value:'Ongole', key:'Andhra Pradesh'},
	{value:'Palacole', key:'Andhra Pradesh'},
	{value:'Palasa Kasibugga', key:'Andhra Pradesh'},
	{value:'Palwancha', key:'Andhra Pradesh'},
	{value:'Parvathipuram', key:'Andhra Pradesh'},
	{value:'Pedana', key:'Andhra Pradesh'},
	{value:'Peddapuram', key:'Andhra Pradesh'},
	{value:'Pithapuram', key:'Andhra Pradesh'},
	{value:'Pondur', key:'Andhra pradesh'},
	{value:'Ponnur', key:'Andhra Pradesh'},
	{value:'Proddatur', key:'Andhra Pradesh'},
	{value:'Punganur', key:'Andhra Pradesh'},
	{value:'Puttur', key:'Andhra Pradesh'},
	{value:'Rajahmundry', key:'Andhra Pradesh'},
	{value:'Rajam', key:'Andhra Pradesh'},
	{value:'Ramachandrapuram', key:'Andhra Pradesh'},
	{value:'Ramagundam', key:'Andhra Pradesh'},
	{value:'Rayachoti', key:'Andhra Pradesh'},
	{value:'Rayadurg', key:'Andhra Pradesh'},
	{value:'Renigunta', key:'Andhra Pradesh'},
	{value:'Repalle', key:'Andhra Pradesh'},
	{value:'Sadasivpet', key:'Andhra Pradesh'},
	{value:'Salur', key:'Andhra Pradesh'},
	{value:'Samalkot', key:'Andhra Pradesh'},
	{value:'Sangareddy', key:'Andhra Pradesh'},
	{value:'Sattenapalle', key:'Andhra Pradesh'},
	{value:'Siddipet', key:'Andhra Pradesh'},
	{value:'Singapur', key:'Andhra Pradesh'},
	{value:'Sircilla', key:'Andhra Pradesh'},
	{value:'Srikakulam', key:'Andhra Pradesh'},
	{value:'Srikalahasti', key:'Andhra Pradesh'},
	{value:'Suryapet', key:'Andhra Pradesh'},
	{value:'Tadepalligudem', key:'Andhra Pradesh'},
	{value:'Tadpatri', key:'Andhra Pradesh'},
	{value:'Tandur', key:'Andhra Pradesh'},
	{value:'Tanuku', key:'Andhra Pradesh'},
	{value:'Tenali', key:'Andhra Pradesh'},
	{value:'Tirupati', key:'Andhra Pradesh'},
	{value:'Tuni', key:'Andhra Pradesh'},
	{value:'Uravakonda', key:'Andhra Pradesh'},
	{value:'Venkatagiri', key:'Andhra Pradesh'},
	{value:'Vicarabad', key:'Andhra Pradesh'},
	{value:'Vijayawada', key:'Andhra Pradesh'},
	{value:'Vinukonda', key:'Andhra Pradesh'},
	{value:'Visakhapatnam', key:'Andhra Pradesh'},
	{value:'Vizianagaram', key:'Andhra Pradesh'},
	{value:'Wanaparthy', key:'Andhra Pradesh'},
	{value:'Warangal', key:'Andhra Pradesh'},
	{value:'Yellandu', key:'Andhra Pradesh'},
	{value:'Yemmiganur', key:'Andhra Pradesh'},
	{value:'Yerraguntla', key:'Andhra Pradesh'},
	{value:'Zahirabad', key:'Andhra Pradesh'},
	{value:'Rajampet', key:'Andhra Pradesh'},
	{value:'Along', key:'Arunachal Pradesh'},
	{value:'Bomdila', key:'Arunachal Pradesh'},
	{value:'Itanagar', key:'Arunachal Pradesh'},
	{value:'Naharlagun', key:'Arunachal Pradesh'},
	{value:'Pasighat', key:'Arunachal Pradesh'},
	{value:'Abhayapuri', key:'Assam'},
	{value:'Amguri', key:'Assam'},
	{value:'Anandnagaar', key:'Assam'},
	{value:'Barpeta', key:'Assam'},
	{value:'Barpeta Road', key:'Assam'},
	{value:'Bilasipara', key:'Assam'},
	{value:'Bongaigaon', key:'Assam'},
	{value:'Dhekiajuli', key:'Assam'},
	{value:'Dhubri', key:'Assam'},
	{value:'Dibrugarh', key:'Assam'},
	{value:'Digboi', key:'Assam'},
	{value:'Diphu', key:'Assam'},
	{value:'Dispur', key:'Assam'},
	{value:'Gauripur', key:'Assam'},
	{value:'Goalpara', key:'Assam'},
	{value:'Golaghat', key:'Assam'},
	{value:'Guwahati', key:'Assam'},
	{value:'Haflong', key:'Assam'},
	{value:'Hailakandi', key:'Assam'},
	{value:'Hojai', key:'Assam'},
	{value:'Jorhat', key:'Assam'},
	{value:'Karimganj', key:'Assam'},
	{value:'Kokrajhar', key:'Assam'},
	{value:'Lanka', key:'Assam'},
	{value:'Lumding', key:'Assam'},
	{value:'Mangaldoi', key:'Assam'},
	{value:'Mankachar', key:'Assam'},
	{value:'Margherita', key:'Assam'},
	{value:'Mariani', key:'Assam'},
	{value:'Marigaon', key:'Assam'},
	{value:'Nagaon', key:'Assam'},
	{value:'Nalbari', key:'Assam'},
	{value:'North Lakhimpur', key:'Assam'},
	{value:'Rangia', key:'Assam'},
	{value:'Sibsagar', key:'Assam'},
	{value:'Silapathar', key:'Assam'},
	{value:'Silchar', key:'Assam'},
	{value:'Tezpur', key:'Assam'},
	{value:'Tinsukia', key:'Assam'},
	{value:'Amarpur', key:'Bihar'},
	{value:'Araria', key:'Bihar'},
	{value:'Areraj', key:'Bihar'},
	{value:'Arrah', key:'Bihar'},
	{value:'Asarganj', key:'Bihar'},
	{value:'Aurangabad', key:'Bihar'},
	{value:'Bagaha', key:'Bihar'},
	{value:'Bahadurganj', key:'Bihar'},
	{value:'Bairgania', key:'Bihar'},
	{value:'Bakhtiarpur', key:'Bihar'},
	{value:'Banka', key:'Bihar'},
	{value:'Banmankhi Bazar', key:'Bihar'},
	{value:'Barahiya', key:'Bihar'},
	{value:'Barauli', key:'Bihar'},
	{value:'Barbigha', key:'Bihar'},
	{value:'Barh', key:'Bihar'},
	{value:'Begusarai', key:'Bihar'},
	{value:'Behea', key:'Bihar'},
	{value:'Bettiah', key:'Bihar'},
	{value:'Bhabua', key:'Bihar'},
	{value:'Bhagalpur', key:'Bihar'},
	{value:'Bihar Sharif', key:'Bihar'},
	{value:'Bikramganj', key:'Bihar'},
	{value:'Bodh Gaya', key:'Bihar'},
	{value:'Buxar', key:'Bihar'},
	{value:'Chandan Bara', key:'Bihar'},
	{value:'Chanpatia', key:'Bihar'},
	{value:'Chhapra', key:'Bihar'},
	{value:'Colgong', key:'Bihar'},
	{value:'Dalsinghsarai', key:'Bihar'},
	{value:'Darbhanga', key:'Bihar'},
	{value:'Daudnagar', key:'Bihar'},
	{value:'Dehri-on-Sone', key:'Bihar'},
	{value:'Dhaka', key:'Bihar'},
	{value:'Dighwara', key:'Bihar'},
	{value:'Dumraon', key:'Bihar'},
	{value:'Fatwah', key:'Bihar'},
	{value:'Forbesganj', key:'Bihar'},
	{value:'Gaya', key:'Bihar'},
	{value:'Gogri Jamalpur', key:'Bihar'},
	{value:'Gopalganj', key:'Bihar'},
	{value:'Hajipur', key:'Bihar'},
	{value:'Hilsa', key:'Bihar'},
	{value:'Hisua', key:'Bihar'},
	{value:'Islampur', key:'Bihar'},
	{value:'Jagdispur', key:'Bihar'},
	{value:'Jamalpur', key:'Bihar'},
	{value:'Jamui', key:'Bihar'},
	{value:'Jehanabad', key:'Bihar'},
	{value:'Jhajha', key:'Bihar'},
	{value:'Jhanjharpur', key:'Bihar'},
	{value:'Jogabani', key:'Bihar'},
	{value:'Kanti', key:'Bihar'},
	{value:'Katihar', key:'Bihar'},
	{value:'Khagaria', key:'Bihar'},
	{value:'Kharagpur', key:'Bihar'},
	{value:'Kishanganj', key:'Bihar'},
	{value:'Lakhisarai', key:'Bihar'},
	{value:'Lalganj', key:'Bihar'},
	{value:'Madhepura', key:'Bihar'},
	{value:'Madhubani', key:'Bihar'},
	{value:'Maharajganj', key:'Bihar'},
	{value:'Mahnar Bazar', key:'Bihar'},
	{value:'Makhdumpur', key:'Bihar'},
	{value:'Maner', key:'Bihar'},
	{value:'Manihari', key:'Bihar'},
	{value:'Marhaura', key:'Bihar'},
	{value:'Masaurhi', key:'Bihar'},
	{value:'Mirganj', key:'Bihar'},
	{value:'Mokameh', key:'Bihar'},
	{value:'Motihari', key:'Bihar'},
	{value:'Motipur', key:'Bihar'},
	{value:'Munger', key:'Bihar'},
	{value:'Murliganj', key:'Bihar'},
	{value:'Muzaffarpur', key:'Bihar'},
	{value:'Narkatiaganj', key:'Bihar'},
	{value:'Naugachhia', key:'Bihar'},
	{value:'Nawada', key:'Bihar'},
	{value:'Nokha', key:'Bihar'},
	{value:'Patna', key:'Bihar'},
	{value:'Piro', key:'Bihar'},
	{value:'Purnia', key:'Bihar'},
	{value:'Rafiganj', key:'Bihar'},
	{value:'Rajgir', key:'Bihar'},
	{value:'Ramnagar', key:'Bihar'},
	{value:'Raxaul Bazar', key:'Bihar'},
	{value:'Revelganj', key:'Bihar'},
	{value:'Rosera', key:'Bihar'},
	{value:'Saharsa', key:'Bihar'},
	{value:'Samastipur', key:'Bihar'},
	{value:'Sasaram', key:'Bihar'},
	{value:'Sheikhpura', key:'Bihar'},
	{value:'Sheohar', key:'Bihar'},
	{value:'Sherghati', key:'Bihar'},
	{value:'Silao', key:'Bihar'},
	{value:'Sitamarhi', key:'Bihar'},
	{value:'Siwan', key:'Bihar'},
	{value:'Sonepur', key:'Bihar'},
	{value:'Sugauli', key:'Bihar'},
	{value:'Sultanganj', key:'Bihar'},
	{value:'Supaul', key:'Bihar'},
	{value:'Warisaliganj', key:'Bihar'},
	{value:'Ahiwara', key:'Chhattisgarh'},
	{value:'Akaltara', key:'Chhattisgarh'},
	{value:'Ambagarh Chowki', key:'Chhattisgarh'},
	{value:'Ambikapur', key:'Chhattisgarh'},
	{value:'Arang', key:'Chhattisgarh'},
	{value:'Bade Bacheli', key:'Chhattisgarh'},
	{value:'Balod', key:'Chhattisgarh'},
	{value:'Baloda Bazar', key:'Chhattisgarh'},
	{value:'Bemetra', key:'Chhattisgarh'},
	{value:'Bhatapara', key:'Chhattisgarh'},
	{value:'Bilaspur', key:'Chhattisgarh'},
	{value:'Birgaon', key:'Chhattisgarh'},
	{value:'Champa', key:'Chhattisgarh'},
	{value:'Chirmiri', key:'Chhattisgarh'},
	{value:'Dalli-Rajhara', key:'Chhattisgarh'},
	{value:'Dhamtari', key:'Chhattisgarh'},
	{value:'Dipka', key:'Chhattisgarh'},
	{value:'Dongargarh', key:'Chhattisgarh'},
	{value:'Durg-Bhilai Nagar', key:'Chhattisgarh'},
	{value:'Gobranawapara', key:'Chhattisgarh'},
	{value:'Jagdalpur', key:'Chhattisgarh'},
	{value:'Janjgir', key:'Chhattisgarh'},
	{value:'Jashpurnagar', key:'Chhattisgarh'},
	{value:'Kanker', key:'Chhattisgarh'},
	{value:'Kawardha', key:'Chhattisgarh'},
	{value:'Kondagaon', key:'Chhattisgarh'},
	{value:'Korba', key:'Chhattisgarh'},
	{value:'Mahasamund', key:'Chhattisgarh'},
	{value:'Mahendragarh', key:'Chhattisgarh'},
	{value:'Mungeli', key:'Chhattisgarh'},
	{value:'Naila Janjgir', key:'Chhattisgarh'},
	{value:'Raigarh', key:'Chhattisgarh'},
	{value:'Raipur', key:'Chhattisgarh'},
	{value:'Rajnandgaon', key:'Chhattisgarh'},
	{value:'Sakti', key:'Chhattisgarh'},
	{value:'Tilda Newra', key:'Chhattisgarh'},
	{value:'Amli', key:'Dadra & Nagar Haveli'},
	{value:'Silvassa', key:'Dadra & Nagar Haveli'},
	{value:'Daman and Diu', key:'Daman & Diu'},
	{value:'Asola', key:'Delhi'},
	{value:'Delhi', key:'Delhi'},
	{value:'Aldona', key:'Goa'},
	{value:'Curchorem Cacora', key:'Goa'},
	{value:'Madgaon', key:'Goa'},
	{value:'Mapusa', key:'Goa'},
	{value:'Margao', key:'Goa'},
	{value:'Marmagao', key:'Goa'},
	{value:'Panaji', key:'Goa'},
	{value:'Ahmedabad', key:'Gujarat'},
	{value:'Amreli', key:'Gujarat'},
	{value:'Anand', key:'Gujarat'},
	{value:'Ankleshwar', key:'Gujarat'},
	{value:'Bharuch', key:'Gujarat'},
	{value:'Bhavnagar', key:'Gujarat'},
	{value:'Bhuj', key:'Gujarat'},
	{value:'Cambay', key:'Gujarat'},
	{value:'Dahod', key:'Gujarat'},
	{value:'Deesa', key:'Gujarat'},
	{value:'Dharampur', key:' India'},
	{value:'Dholka', key:'Gujarat'},
	{value:'Gandhinagar', key:'Gujarat'},
	{value:'Godhra', key:'Gujarat'},
	{value:'Himatnagar', key:'Gujarat'},
	{value:'Idar', key:'Gujarat'},
	{value:'Jamnagar', key:'Gujarat'},
	{value:'Junagadh', key:'Gujarat'},
	{value:'Kadi', key:'Gujarat'},
	{value:'Kalavad', key:'Gujarat'},
	{value:'Kalol', key:'Gujarat'},
	{value:'Kapadvanj', key:'Gujarat'},
	{value:'Karjan', key:'Gujarat'},
	{value:'Keshod', key:'Gujarat'},
	{value:'Khambhalia', key:'Gujarat'},
	{value:'Khambhat', key:'Gujarat'},
	{value:'Kheda', key:'Gujarat'},
	{value:'Khedbrahma', key:'Gujarat'},
	{value:'Kheralu', key:'Gujarat'},
	{value:'Kodinar', key:'Gujarat'},
	{value:'Lathi', key:'Gujarat'},
	{value:'Limbdi', key:'Gujarat'},
	{value:'Lunawada', key:'Gujarat'},
	{value:'Mahesana', key:'Gujarat'},
	{value:'Mahuva', key:'Gujarat'},
	{value:'Manavadar', key:'Gujarat'},
	{value:'Mandvi', key:'Gujarat'},
	{value:'Mangrol', key:'Gujarat'},
	{value:'Mansa', key:'Gujarat'},
	{value:'Mehmedabad', key:'Gujarat'},
	{value:'Modasa', key:'Gujarat'},
	{value:'Morvi', key:'Gujarat'},
	{value:'Nadiad', key:'Gujarat'},
	{value:'Navsari', key:'Gujarat'},
	{value:'Padra', key:'Gujarat'},
	{value:'Palanpur', key:'Gujarat'},
	{value:'Palitana', key:'Gujarat'},
	{value:'Pardi', key:'Gujarat'},
	{value:'Patan', key:'Gujarat'},
	{value:'Petlad', key:'Gujarat'},
	{value:'Porbandar', key:'Gujarat'},
	{value:'Radhanpur', key:'Gujarat'},
	{value:'Rajkot', key:'Gujarat'},
	{value:'Rajpipla', key:'Gujarat'},
	{value:'Rajula', key:'Gujarat'},
	{value:'Ranavav', key:'Gujarat'},
	{value:'Rapar', key:'Gujarat'},
	{value:'Salaya', key:'Gujarat'},
	{value:'Sanand', key:'Gujarat'},
	{value:'Savarkundla', key:'Gujarat'},
	{value:'Sidhpur', key:'Gujarat'},
	{value:'Sihor', key:'Gujarat'},
	{value:'Songadh', key:'Gujarat'},
	{value:'Surat', key:'Gujarat'},
	{value:'Talaja', key:'Gujarat'},
	{value:'Thangadh', key:'Gujarat'},
	{value:'Tharad', key:'Gujarat'},
	{value:'Umbergaon', key:'Gujarat'},
	{value:'Umreth', key:'Gujarat'},
	{value:'Una', key:'Gujarat'},
	{value:'Unjha', key:'Gujarat'},
	{value:'Upleta', key:'Gujarat'},
	{value:'Vadnagar', key:'Gujarat'},
	{value:'Vadodara', key:'Gujarat'},
	{value:'Valsad', key:'Gujarat'},
	{value:'Vapi', key:'Gujarat'},
	{value:'Veraval', key:'Gujarat'},
	{value:'Vijapur', key:'Gujarat'},
	{value:'Viramgam', key:'Gujarat'},
	{value:'Visnagar', key:'Gujarat'},
	{value:'Vyara', key:'Gujarat'},
	{value:'Wadhwan', key:'Gujarat'},
	{value:'Wankaner', key:'Gujarat'},
	{value:'Adalaj', key:'Gujrat'},
	{value:'Adityana', key:'Gujrat'},
	{value:'Alang', key:'Gujrat'},
	{value:'Ambaji', key:'Gujrat'},
	{value:'Ambaliyasan', key:'Gujrat'},
	{value:'Andada', key:'Gujrat'},
	{value:'Anjar', key:'Gujrat'},
	{value:'Anklav', key:'Gujrat'},
	{value:'Antaliya', key:'Gujrat'},
	{value:'Arambhada', key:'Gujrat'},
	{value:'Atul', key:'Gujrat'},
	{value:'Ballabhgarh', key:'Haryana'},
	{value:'Ambala', key:'Haryana'},
	{value:'Asankhurd', key:'Haryana'},
	{value:'Assandh', key:'Haryana'},
	{value:'Ateli', key:'Haryana'},
	{value:'Babiyal', key:'Haryana'},
	{value:'Bahadurgarh', key:'Haryana'},
	{value:'Barwala', key:'Haryana'},
	{value:'Bhiwani', key:'Haryana'},
	{value:'Charkhi Dadri', key:'Haryana'},
	{value:'Cheeka', key:'Haryana'},
	{value:'Ellenabad 2', key:'Haryana'},
	{value:'Faridabad', key:'Haryana'},
	{value:'Fatehabad', key:'Haryana'},
	{value:'Ganaur', key:'Haryana'},
	{value:'Gharaunda', key:'Haryana'},
	{value:'Gohana', key:'Haryana'},
	{value:'Gurgaon', key:'Haryana'},
	{value:'Haibat(Yamuna Nagar)', key:'Haryana'},
	{value:'Hansi', key:'Haryana'},
	{value:'Hisar', key:'Haryana'},
	{value:'Hodal', key:'Haryana'},
	{value:'Jhajjar', key:'Haryana'},
	{value:'Jind', key:'Haryana'},
	{value:'Kaithal', key:'Haryana'},
	{value:'Kalan Wali', key:'Haryana'},
	{value:'Kalka', key:'Haryana'},
	{value:'Karnal', key:'Haryana'},
	{value:'Ladwa', key:'Haryana'},
	{value:'Mandi Dabwali', key:'Haryana'},
	{value:'Narnaul', key:'Haryana'},
	{value:'Narwana', key:'Haryana'},
	{value:'Palwal', key:'Haryana'},
	{value:'Panchkula', key:'Haryana'},
	{value:'Panipat', key:'Haryana'},
	{value:'Pehowa', key:'Haryana'},
	{value:'Pinjore', key:'Haryana'},
	{value:'Rania', key:'Haryana'},
	{value:'Ratia', key:'Haryana'},
	{value:'Rewari', key:'Haryana'},
	{value:'Rohtak', key:'Haryana'},
	{value:'Safidon', key:'Haryana'},
	{value:'Samalkha', key:'Haryana'},
	{value:'Shahbad', key:'Haryana'},
	{value:'Sirsa', key:'Haryana'},
	{value:'Sohna', key:'Haryana'},
	{value:'Sonipat', key:'Haryana'},
	{value:'Taraori', key:'Haryana'},
	{value:'Thanesar', key:'Haryana'},
	{value:'Tohana', key:'Haryana'},
	{value:'Yamunanagar', key:'Haryana'},
	{value:'Arki', key:'Himachal Pradesh'},
	{value:'Baddi', key:'Himachal Pradesh'},
	{value:'Bilaspur', key:'Himachal Pradesh'},
	{value:'Chamba', key:'Himachal Pradesh'},
	{value:'Dalhousie', key:'Himachal Pradesh'},
	{value:'Dharamsala', key:'Himachal Pradesh'},
	{value:'Hamirpur', key:'Himachal Pradesh'},
	{value:'Mandi', key:'Himachal Pradesh'},
	{value:'Nahan', key:'Himachal Pradesh'},
	{value:'Shimla', key:'Himachal Pradesh'},
	{value:'Solan', key:'Himachal Pradesh'},
	{value:'Sundarnagar', key:'Himachal Pradesh'},
	{value:'Jammu', key:'Jammu & Kashmir'},
	{value:'Achabbal', key:'Jammu & Kashmir'},
	{value:'Akhnoor', key:'Jammu & Kashmir'},
	{value:'Anantnag', key:'Jammu & Kashmir'},
	{value:'Arnia', key:'Jammu & Kashmir'},
	{value:'Awantipora', key:'Jammu & Kashmir'},
	{value:'Bandipore', key:'Jammu & Kashmir'},
	{value:'Baramula', key:'Jammu & Kashmir'},
	{value:'Kathua', key:'Jammu & Kashmir'},
	{value:'Leh', key:'Jammu & Kashmir'},
	{value:'Punch', key:'Jammu & Kashmir'},
	{value:'Rajauri', key:'Jammu & Kashmir'},
	{value:'Sopore', key:'Jammu & Kashmir'},
	{value:'Srinagar', key:'Jammu & Kashmir'},
	{value:'Udhampur', key:'Jammu & Kashmir'},
	{value:'Amlabad', key:'Jharkhand'},
	{value:'Ara', key:'Jharkhand'},
	{value:'Barughutu', key:'Jharkhand'},
	{value:'Bokaro Steel value', key:'Jharkhand'},
	{value:'Chaibasa', key:'Jharkhand'},
	{value:'Chakradharpur', key:'Jharkhand'},
	{value:'Chandrapura', key:'Jharkhand'},
	{value:'Chatra', key:'Jharkhand'},
	{value:'Chirkunda', key:'Jharkhand'},
	{value:'Churi', key:'Jharkhand'},
	{value:'Daltonganj', key:'Jharkhand'},
	{value:'Deoghar', key:'Jharkhand'},
	{value:'Dhanbad', key:'Jharkhand'},
	{value:'Dumka', key:'Jharkhand'},
	{value:'Garhwa', key:'Jharkhand'},
	{value:'Ghatshila', key:'Jharkhand'},
	{value:'Giridih', key:'Jharkhand'},
	{value:'Godda', key:'Jharkhand'},
	{value:'Gomoh', key:'Jharkhand'},
	{value:'Gumia', key:'Jharkhand'},
	{value:'Gumla', key:'Jharkhand'},
	{value:'Hazaribag', key:'Jharkhand'},
	{value:'Hussainabad', key:'Jharkhand'},
	{value:'Jamshedpur', key:'Jharkhand'},
	{value:'Jamtara', key:'Jharkhand'},
	{value:'Jhumri Tilaiya', key:'Jharkhand'},
	{value:'Khunti', key:'Jharkhand'},
	{value:'Lohardaga', key:'Jharkhand'},
	{value:'Madhupur', key:'Jharkhand'},
	{value:'Mihijam', key:'Jharkhand'},
	{value:'Musabani', key:'Jharkhand'},
	{value:'Pakaur', key:'Jharkhand'},
	{value:'Patratu', key:'Jharkhand'},
	{value:'Phusro', key:'Jharkhand'},
	{value:'Ramngarh', key:'Jharkhand'},
	{value:'Ranchi', key:'Jharkhand'},
	{value:'Sahibganj', key:'Jharkhand'},
	{value:'Saunda', key:'Jharkhand'},
	{value:'Simdega', key:'Jharkhand'},
	{value:'Tenu Dam-cum- Kathhara', key:'Jharkhand'},
	{value:'Arasikere', key:'Karnataka'},
	{value:'Bangalore', key:'Karnataka'},
	{value:'Belgaum', key:'Karnataka'},
	{value:'Bellary', key:'Karnataka'},
	{value:'Chamrajnagar', key:'Karnataka'},
	{value:'Chikkaballapur', key:'Karnataka'},
	{value:'Chintamani', key:'Karnataka'},
	{value:'Chitradurga', key:'Karnataka'},
	{value:'Gulbarga', key:'Karnataka'},
	{value:'Gundlupet', key:'Karnataka'},
	{value:'Hassan', key:'Karnataka'},
	{value:'Hospet', key:'Karnataka'},
	{value:'Hubli', key:'Karnataka'},
	{value:'Karkala', key:'Karnataka'},
	{value:'Karwar', key:'Karnataka'},
	{value:'Kolar', key:'Karnataka'},
	{value:'Kota', key:'Karnataka'},
	{value:'Lakshmeshwar', key:'Karnataka'},
	{value:'Lingsugur', key:'Karnataka'},
	{value:'Maddur', key:'Karnataka'},
	{value:'Madhugiri', key:'Karnataka'},
	{value:'Madikeri', key:'Karnataka'},
	{value:'Magadi', key:'Karnataka'},
	{value:'Mahalingpur', key:'Karnataka'},
	{value:'Malavalli', key:'Karnataka'},
	{value:'Malur', key:'Karnataka'},
	{value:'Mandya', key:'Karnataka'},
	{value:'Mangalore', key:'Karnataka'},
	{value:'Manvi', key:'Karnataka'},
	{value:'Mudalgi', key:'Karnataka'},
	{value:'Mudbidri', key:'Karnataka'},
	{value:'Muddebihal', key:'Karnataka'},
	{value:'Mudhol', key:'Karnataka'},
	{value:'Mulbagal', key:'Karnataka'},
	{value:'Mundargi', key:'Karnataka'},
	{value:'Mysore', key:'Karnataka'},
	{value:'Nanjangud', key:'Karnataka'},
	{value:'Pavagada', key:'Karnataka'},
	{value:'Puttur', key:'Karnataka'},
	{value:'Rabkavi Banhatti', key:'Karnataka'},
	{value:'Raichur', key:'Karnataka'},
	{value:'Ramanagaram', key:'Karnataka'},
	{value:'Ramdurg', key:'Karnataka'},
	{value:'Ranibennur', key:'Karnataka'},
	{value:'Robertson Pet', key:'Karnataka'},
	{value:'Ron', key:'Karnataka'},
	{value:'Sadalgi', key:'Karnataka'},
	{value:'Sagar', key:'Karnataka'},
	{value:'Sakleshpur', key:'Karnataka'},
	{value:'Sandur', key:'Karnataka'},
	{value:'Sankeshwar', key:'Karnataka'},
	{value:'Saundatti-Yellamma', key:'Karnataka'},
	{value:'Savanur', key:'Karnataka'},
	{value:'Sedam', key:'Karnataka'},
	{value:'Shahabad', key:'Karnataka'},
	{value:'Shahpur', key:'Karnataka'},
	{value:'Shiggaon', key:'Karnataka'},
	{value:'Shikapur', key:'Karnataka'},
	{value:'Shimoga', key:'Karnataka'},
	{value:'Shorapur', key:'Karnataka'},
	{value:'Shrirangapattana', key:'Karnataka'},
	{value:'Sidlaghatta', key:'Karnataka'},
	{value:'Sindgi', key:'Karnataka'},
	{value:'Sindhnur', key:'Karnataka'},
	{value:'Sira', key:'Karnataka'},
	{value:'Sirsi', key:'Karnataka'},
	{value:'Siruguppa', key:'Karnataka'},
	{value:'Srinivaspur', key:'Karnataka'},
	{value:'Talikota', key:'Karnataka'},
	{value:'Tarikere', key:'Karnataka'},
	{value:'Tekkalakota', key:'Karnataka'},
	{value:'Terdal', key:'Karnataka'},
	{value:'Tiptur', key:'Karnataka'},
	{value:'Tumkur', key:'Karnataka'},
	{value:'Udupi', key:'Karnataka'},
	{value:'Vijayapura', key:'Karnataka'},
	{value:'Wadi', key:'Karnataka'},
	{value:'Yadgir', key:'Karnataka'},
	{value:'Adoor', key:'Kerala'},
	{value:'Akathiyoor', key:'Kerala'},
	{value:'Alappuzha', key:'Kerala'},
	{value:'Ancharakandy', key:'Kerala'},
	{value:'Aroor', key:'Kerala'},
	{value:'Ashtamichira', key:'Kerala'},
	{value:'Attingal', key:'Kerala'},
	{value:'Avinissery', key:'Kerala'},
	{value:'Chalakudy', key:'Kerala'},
	{value:'Changanassery', key:'Kerala'},
	{value:'Chendamangalam', key:'Kerala'},
	{value:'Chengannur', key:'Kerala'},
	{value:'Cherthala', key:'Kerala'},
	{value:'Cheruthazham', key:'Kerala'},
	{value:'Chittur-Thathamangalam', key:'Kerala'},
	{value:'Chockli', key:'Kerala'},
	{value:'Erattupetta', key:'Kerala'},
	{value:'Guruvayoor', key:'Kerala'},
	{value:'Irinjalakuda', key:'Kerala'},
	{value:'Kadirur', key:'Kerala'},
	{value:'Kalliasseri', key:'Kerala'},
	{value:'Kalpetta', key:'Kerala'},
	{value:'Kanhangad', key:'Kerala'},
	{value:'Kanjikkuzhi', key:'Kerala'},
	{value:'Kannur', key:'Kerala'},
	{value:'Kasaragod', key:'Kerala'},
	{value:'Kayamkulam', key:'Kerala'},
	{value:'Kochi', key:'Kerala'},
	{value:'Kodungallur', key:'Kerala'},
	{value:'Kollam', key:'Kerala'},
	{value:'Koothuparamba', key:'Kerala'},
	{value:'Kothamangalam', key:'Kerala'},
	{value:'Kottayam', key:'Kerala'},
	{value:'Kozhikode', key:'Kerala'},
	{value:'Kunnamkulam', key:'Kerala'},
	{value:'Malappuram', key:'Kerala'},
	{value:'Mattannur', key:'Kerala'},
	{value:'Mavelikkara', key:'Kerala'},
	{value:'Mavoor', key:'Kerala'},
	{value:'Muvattupuzha', key:'Kerala'},
	{value:'Nedumangad', key:'Kerala'},
	{value:'Neyyattinkara', key:'Kerala'},
	{value:'Ottappalam', key:'Kerala'},
	{value:'Palai', key:'Kerala'},
	{value:'Palakkad', key:'Kerala'},
	{value:'Panniyannur', key:'Kerala'},
	{value:'Pappinisseri', key:'Kerala'},
	{value:'Paravoor', key:'Kerala'},
	{value:'Pathanamthitta', key:'Kerala'},
	{value:'Payyannur', key:'Kerala'},
	{value:'Peringathur', key:'Kerala'},
	{value:'Perinthalmanna', key:'Kerala'},
	{value:'Perumbavoor', key:'Kerala'},
	{value:'Ponnani', key:'Kerala'},
	{value:'Punalur', key:'Kerala'},
	{value:'Quilandy', key:'Kerala'},
	{value:'Shoranur', key:'Kerala'},
	{value:'Taliparamba', key:'Kerala'},
	{value:'Thiruvalla', key:'Kerala'},
	{value:'Thiruvananthapuram', key:'Kerala'},
	{value:'Thodupuzha', key:'Kerala'},
	{value:'Thrissur', key:'Kerala'},
	{value:'Tirur', key:'Kerala'},
	{value:'Vadakara', key:'Kerala'},
	{value:'Vaikom', key:'Kerala'},
	{value:'Varkala', key:'Kerala'},
	{value:'Kavaratti', key:'Lakshadweep'},
	{value:'Ashok Nagar', key:'Madhya Pradesh'},
	{value:'Balaghat', key:'Madhya Pradesh'},
	{value:'Betul', key:'Madhya Pradesh'},
	{value:'Bhopal', key:'Madhya Pradesh'},
	{value:'Burhanpur', key:'Madhya Pradesh'},
	{value:'Chhatarpur', key:'Madhya Pradesh'},
	{value:'Dabra', key:'Madhya Pradesh'},
	{value:'Datia', key:'Madhya Pradesh'},
	{value:'Dewas', key:'Madhya Pradesh'},
	{value:'Dhar', key:'Madhya Pradesh'},
	{value:'Fatehabad', key:'Madhya Pradesh'},
	{value:'Gwalior', key:'Madhya Pradesh'},
	{value:'Indore', key:'Madhya Pradesh'},
	{value:'Itarsi', key:'Madhya Pradesh'},
	{value:'Jabalpur', key:'Madhya Pradesh'},
	{value:'Katni', key:'Madhya Pradesh'},
	{value:'Kotma', key:'Madhya Pradesh'},
	{value:'Lahar', key:'Madhya Pradesh'},
	{value:'Lundi', key:'Madhya Pradesh'},
	{value:'Maharajpur', key:'Madhya Pradesh'},
	{value:'Mahidpur', key:'Madhya Pradesh'},
	{value:'Maihar', key:'Madhya Pradesh'},
	{value:'Malajkhand', key:'Madhya Pradesh'},
	{value:'Manasa', key:'Madhya Pradesh'},
	{value:'Manawar', key:'Madhya Pradesh'},
	{value:'Mandideep', key:'Madhya Pradesh'},
	{value:'Mandla', key:'Madhya Pradesh'},
	{value:'Mandsaur', key:'Madhya Pradesh'},
	{value:'Mauganj', key:'Madhya Pradesh'},
	{value:'Mhow Cantonment', key:'Madhya Pradesh'},
	{value:'Mhowgaon', key:'Madhya Pradesh'},
	{value:'Morena', key:'Madhya Pradesh'},
	{value:'Multai', key:'Madhya Pradesh'},
	{value:'Murwara', key:'Madhya Pradesh'},
	{value:'Nagda', key:'Madhya Pradesh'},
	{value:'Nainpur', key:'Madhya Pradesh'},
	{value:'Narsinghgarh', key:'Madhya Pradesh'},
	{value:'Neemuch', key:'Madhya Pradesh'},
	{value:'Nepanagar', key:'Madhya Pradesh'},
	{value:'Niwari', key:'Madhya Pradesh'},
	{value:'Nowgong', key:'Madhya Pradesh'},
	{value:'Nowrozabad', key:'Madhya Pradesh'},
	{value:'Pachore', key:'Madhya Pradesh'},
	{value:'Pali', key:'Madhya Pradesh'},
	{value:'Panagar', key:'Madhya Pradesh'},
	{value:'Pandhurna', key:'Madhya Pradesh'},
	{value:'Panna', key:'Madhya Pradesh'},
	{value:'Pasan', key:'Madhya Pradesh'},
	{value:'Pipariya', key:'Madhya Pradesh'},
	{value:'Pithampur', key:'Madhya Pradesh'},
	{value:'Porsa', key:'Madhya Pradesh'},
	{value:'Prithvipur', key:'Madhya Pradesh'},
	{value:'Raghogarh-Vijaypur', key:'Madhya Pradesh'},
	{value:'Rahatgarh', key:'Madhya Pradesh'},
	{value:'Raisen', key:'Madhya Pradesh'},
	{value:'Rajgarh', key:'Madhya Pradesh'},
	{value:'Ratlam', key:'Madhya Pradesh'},
	{value:'Rau', key:'Madhya Pradesh'},
	{value:'Rehli', key:'Madhya Pradesh'},
	{value:'Rewa', key:'Madhya Pradesh'},
	{value:'Sabalgarh', key:'Madhya Pradesh'},
	{value:'Sagar', key:'Madhya Pradesh'},
	{value:'Sanawad', key:'Madhya Pradesh'},
	{value:'Sarangpur', key:'Madhya Pradesh'},
	{value:'Sarni', key:'Madhya Pradesh'},
	{value:'Satna', key:'Madhya Pradesh'},
	{value:'Sausar', key:'Madhya Pradesh'},
	{value:'Sehore', key:'Madhya Pradesh'},
	{value:'Sendhwa', key:'Madhya Pradesh'},
	{value:'Seoni', key:'Madhya Pradesh'},
	{value:'Seoni-Malwa', key:'Madhya Pradesh'},
	{value:'Shahdol', key:'Madhya Pradesh'},
	{value:'Shajapur', key:'Madhya Pradesh'},
	{value:'Shamgarh', key:'Madhya Pradesh'},
	{value:'Sheopur', key:'Madhya Pradesh'},
	{value:'Shivpuri', key:'Madhya Pradesh'},
	{value:'Shujalpur', key:'Madhya Pradesh'},
	{value:'Sidhi', key:'Madhya Pradesh'},
	{value:'Sihora', key:'Madhya Pradesh'},
	{value:'Singrauli', key:'Madhya Pradesh'},
	{value:'Sironj', key:'Madhya Pradesh'},
	{value:'Sohagpur', key:'Madhya Pradesh'},
	{value:'Tarana', key:'Madhya Pradesh'},
	{value:'Tikamgarh', key:'Madhya Pradesh'},
	{value:'Ujhani', key:'Madhya Pradesh'},
	{value:'Ujjain', key:'Madhya Pradesh'},
	{value:'Umaria', key:'Madhya Pradesh'},
	{value:'Vidisha', key:'Madhya Pradesh'},
	{value:'Wara Seoni', key:'Madhya Pradesh'},
	{value:'Ahmednagar', key:'Maharashtra'},
	{value:'Akola', key:'Maharashtra'},
	{value:'Amravati', key:'Maharashtra'},
	{value:'Aurangabad', key:'Maharashtra'},
	{value:'Baramati', key:'Maharashtra'},
	{value:'Chalisgaon', key:'Maharashtra'},
	{value:'Chinchani', key:'Maharashtra'},
	{value:'Devgarh', key:'Maharashtra'},
	{value:'Dhule', key:'Maharashtra'},
	{value:'Dombivli', key:'Maharashtra'},
	{value:'Durgapur', key:'Maharashtra'},
	{value:'Ichalkaranji', key:'Maharashtra'},
	{value:'Jalna', key:'Maharashtra'},
	{value:'Kalyan', key:'Maharashtra'},
	{value:'Latur', key:'Maharashtra'},
	{value:'Loha', key:'Maharashtra'},
	{value:'Lonar', key:'Maharashtra'},
	{value:'Lonavla', key:'Maharashtra'},
	{value:'Mahad', key:'Maharashtra'},
	{value:'Mahuli', key:'Maharashtra'},
	{value:'Malegaon', key:'Maharashtra'},
	{value:'Malkapur', key:'Maharashtra'},
	{value:'Manchar', key:'Maharashtra'},
	{value:'Mangalvedhe', key:'Maharashtra'},
	{value:'Mangrulpir', key:'Maharashtra'},
	{value:'Manjlegaon', key:'Maharashtra'},
	{value:'Manmad', key:'Maharashtra'},
	{value:'Manwath', key:'Maharashtra'},
	{value:'Mehkar', key:'Maharashtra'},
	{value:'Mhaswad', key:'Maharashtra'},
	{value:'Miraj', key:'Maharashtra'},
	{value:'Morshi', key:'Maharashtra'},
	{value:'Mukhed', key:'Maharashtra'},
	{value:'Mul', key:'Maharashtra'},
	{value:'Mumbai', key:'Maharashtra'},
	{value:'Murtijapur', key:'Maharashtra'},
	{value:'Nagpur', key:'Maharashtra'},
	{value:'Nalasopara', key:'Maharashtra'},
	{value:'Nanded-Waghala', key:'Maharashtra'},
	{value:'Nandgaon', key:'Maharashtra'},
	{value:'Nandura', key:'Maharashtra'},
	{value:'Nandurbar', key:'Maharashtra'},
	{value:'Narkhed', key:'Maharashtra'},
	{value:'Nashik', key:'Maharashtra'},
	{value:'Navi Mumbai', key:'Maharashtra'},
	{value:'Nawapur', key:'Maharashtra'},
	{value:'Nilanga', key:'Maharashtra'},
	{value:'Osmanabad', key:'Maharashtra'},
	{value:'Ozar', key:'Maharashtra'},
	{value:'Pachora', key:'Maharashtra'},
	{value:'Paithan', key:'Maharashtra'},
	{value:'Palghar', key:'Maharashtra'},
	{value:'Pandharkaoda', key:'Maharashtra'},
	{value:'Pandharpur', key:'Maharashtra'},
	{value:'Panvel', key:'Maharashtra'},
	{value:'Parbhani', key:'Maharashtra'},
	{value:'Parli', key:'Maharashtra'},
	{value:'Parola', key:'Maharashtra'},
	{value:'Partur', key:'Maharashtra'},
	{value:'Pathardi', key:'Maharashtra'},
	{value:'Pathri', key:'Maharashtra'},
	{value:'Patur', key:'Maharashtra'},
	{value:'Pauni', key:'Maharashtra'},
	{value:'Pen', key:'Maharashtra'},
	{value:'Phaltan', key:'Maharashtra'},
	{value:'Pulgaon', key:'Maharashtra'},
	{value:'Pune', key:'Maharashtra'},
	{value:'Purna', key:'Maharashtra'},
	{value:'Pusad', key:'Maharashtra'},
	{value:'Rahuri', key:'Maharashtra'},
	{value:'Rajura', key:'Maharashtra'},
	{value:'Ramtek', key:'Maharashtra'},
	{value:'Ratnagiri', key:'Maharashtra'},
	{value:'Raver', key:'Maharashtra'},
	{value:'Risod', key:'Maharashtra'},
	{value:'Sailu', key:'Maharashtra'},
	{value:'Sangamner', key:'Maharashtra'},
	{value:'Sangli', key:'Maharashtra'},
	{value:'Sangole', key:'Maharashtra'},
	{value:'Sasvad', key:'Maharashtra'},
	{value:'Satana', key:'Maharashtra'},
	{value:'Satara', key:'Maharashtra'},
	{value:'Savner', key:'Maharashtra'},
	{value:'Sawantwadi', key:'Maharashtra'},
	{value:'Shahade', key:'Maharashtra'},
	{value:'Shegaon', key:'Maharashtra'},
	{value:'Shendurjana', key:'Maharashtra'},
	{value:'Shirdi', key:'Maharashtra'},
	{value:'Shirpur-Warwade', key:'Maharashtra'},
	{value:'Shirur', key:'Maharashtra'},
	{value:'Shrigonda', key:'Maharashtra'},
	{value:'Shrirampur', key:'Maharashtra'},
	{value:'Sillod', key:'Maharashtra'},
	{value:'Sinnar', key:'Maharashtra'},
	{value:'Solapur', key:'Maharashtra'},
	{value:'Soyagaon', key:'Maharashtra'},
	{value:'Talegaon Dabhade', key:'Maharashtra'},
	{value:'Talode', key:'Maharashtra'},
	{value:'Tasgaon', key:'Maharashtra'},
	{value:'Tirora', key:'Maharashtra'},
	{value:'Tuljapur', key:'Maharashtra'},
	{value:'Tumsar', key:'Maharashtra'},
	{value:'Uran', key:'Maharashtra'},
	{value:'Uran Islampur', key:'Maharashtra'},
	{value:'Wadgaon Road', key:'Maharashtra'},
	{value:'Wai', key:'Maharashtra'},
	{value:'Wani', key:'Maharashtra'},
	{value:'Wardha', key:'Maharashtra'},
	{value:'Warora', key:'Maharashtra'},
	{value:'Warud', key:'Maharashtra'},
	{value:'Washim', key:'Maharashtra'},
	{value:'Yevla', key:'Maharashtra'},
	{value:'Uchgaon', key:'Maharashtra'},
	{value:'Udgir', key:'Maharashtra'},
	{value:'Umarga', key:'Maharastra'},
	{value:'Umarkhed', key:'Maharastra'},
	{value:'Umred', key:'Maharastra'},
	{value:'Vadgaon Kasba', key:'Maharastra'},
	{value:'Vaijapur', key:'Maharastra'},
	{value:'Vasai', key:'Maharastra'},
	{value:'Virar', key:'Maharastra'},
	{value:'Vita', key:'Maharastra'},
	{value:'Yavatmal', key:'Maharastra'},
	{value:'Yawal', key:'Maharastra'},
	{value:'Imphal', key:'Manipur'},
	{value:'Kakching', key:'Manipur'},
	{value:'Lilong', key:'Manipur'},
	{value:'Mayang Imphal', key:'Manipur'},
	{value:'Thoubal', key:'Manipur'},
	{value:'Jowai', key:'Meghalaya'},
	{value:'Nongstoin', key:'Meghalaya'},
	{value:'Shillong', key:'Meghalaya'},
	{value:'Tura', key:'Meghalaya'},
	{value:'Aizawl', key:'Mizoram'},
	{value:'Champhai', key:'Mizoram'},
	{value:'Lunglei', key:'Mizoram'},
	{value:'Saiha', key:'Mizoram'},
	{value:'Dimapur', key:'Nagaland'},
	{value:'Kohima', key:'Nagaland'},
	{value:'Mokokchung', key:'Nagaland'},
	{value:'Tuensang', key:'Nagaland'},
	{value:'Wokha', key:'Nagaland'},
	{value:'Zunheboto', key:'Nagaland'},
	{value:'Anandapur', key:'Orissa'},
	{value:'Anugul', key:'Orissa'},
	{value:'Asika', key:'Orissa'},
	{value:'Balangir', key:'Orissa'},
	{value:'Balasore', key:'Orissa'},
	{value:'Baleshwar', key:'Orissa'},
	{value:'Bamra', key:'Orissa'},
	{value:'Barbil', key:'Orissa'},
	{value:'Bargarh', key:'Orissa'},
	{value:'Baripada', key:'Orissa'},
	{value:'Basudebpur', key:'Orissa'},
	{value:'Belpahar', key:'Orissa'},
	{value:'Bhadrak', key:'Orissa'},
	{value:'Bhawanipatna', key:'Orissa'},
	{value:'Bhuban', key:'Orissa'},
	{value:'Bhubaneswar', key:'Orissa'},
	{value:'Biramitrapur', key:'Orissa'},
	{value:'Brahmapur', key:'Orissa'},
	{value:'Brajrajnagar', key:'Orissa'},
	{value:'Byasanagar', key:'Orissa'},
	{value:'Cuttack', key:'Orissa'},
	{value:'Debagarh', key:'Orissa'},
	{value:'Dhenkanal', key:'Orissa'},
	{value:'Gunupur', key:'Orissa'},
	{value:'Hinjilicut', key:'Orissa'},
	{value:'Jagatsinghapur', key:'Orissa'},
	{value:'Jajapur', key:'Orissa'},
	{value:'Jaleswar', key:'Orissa'},
	{value:'Jatani', key:'Orissa'},
	{value:'Jeypur', key:'Orissa'},
	{value:'Jharsuguda', key:'Orissa'},
	{value:'Joda', key:'Orissa'},
	{value:'Kantabanji', key:'Orissa'},
	{value:'Karanjia', key:'Orissa'},
	{value:'Kendrapara', key:'Orissa'},
	{value:'Kendujhar', key:'Orissa'},
	{value:'Khordha', key:'Orissa'},
	{value:'Koraput', key:'Orissa'},
	{value:'Malkangiri', key:'Orissa'},
	{value:'Nabarangapur', key:'Orissa'},
	{value:'Paradip', key:'Orissa'},
	{value:'Parlakhemundi', key:'Orissa'},
	{value:'Pattamundai', key:'Orissa'},
	{value:'Phulabani', key:'Orissa'},
	{value:'Puri', key:'Orissa'},
	{value:'Rairangpur', key:'Orissa'},
	{value:'Rajagangapur', key:'Orissa'},
	{value:'Raurkela', key:'Orissa'},
	{value:'Rayagada', key:'Orissa'},
	{value:'Sambalpur', key:'Orissa'},
	{value:'Soro', key:'Orissa'},
	{value:'Sunabeda', key:'Orissa'},
	{value:'Sundargarh', key:'Orissa'},
	{value:'Talcher', key:'Orissa'},
	{value:'Titlagarh', key:'Orissa'},
	{value:'Umarkote', key:'Orissa'},
	{value:'Karaikal', key:'Pondicherry'},
	{value:'Mahe', key:'Pondicherry'},
	{value:'Pondicherry', key:'Pondicherry'},
	{value:'Yanam', key:'Pondicherry'},
	{value:'Ahmedgarh', key:'Punjab'},
	{value:'Amritsar', key:'Punjab'},
	{value:'Barnala', key:'Punjab'},
	{value:'Batala', key:'Punjab'},
	{value:'Bathinda', key:'Punjab'},
	{value:'Bhagha Purana', key:'Punjab'},
	{value:'Budhlada', key:'Punjab'},
	{value:'Chandigarh', key:'Punjab'},
	{value:'Dasua', key:'Punjab'},
	{value:'Dhuri', key:'Punjab'},
	{value:'Dinanagar', key:'Punjab'},
	{value:'Faridkot', key:'Punjab'},
	{value:'Fazilka', key:'Punjab'},
	{value:'Firozpur', key:'Punjab'},
	{value:'Firozpur Cantt.', key:'Punjab'},
	{value:'Giddarbaha', key:'Punjab'},
	{value:'Gobindgarh', key:'Punjab'},
	{value:'Gurdaspur', key:'Punjab'},
	{value:'Hoshiarpur', key:'Punjab'},
	{value:'Jagraon', key:'Punjab'},
	{value:'Jaitu', key:'Punjab'},
	{value:'Jalalabad', key:'Punjab'},
	{value:'Jalandhar', key:'Punjab'},
	{value:'Jalandhar Cantt.', key:'Punjab'},
	{value:'Jandiala', key:'Punjab'},
	{value:'Kapurthala', key:'Punjab'},
	{value:'Karoran', key:'Punjab'},
	{value:'Kartarpur', key:'Punjab'},
	{value:'Khanna', key:'Punjab'},
	{value:'Kharar', key:'Punjab'},
	{value:'Kot Kapura', key:'Punjab'},
	{value:'Kurali', key:'Punjab'},
	{value:'Longowal', key:'Punjab'},
	{value:'Ludhiana', key:'Punjab'},
	{value:'Malerkotla', key:'Punjab'},
	{value:'Malout', key:'Punjab'},
	{value:'Mansa', key:'Punjab'},
	{value:'Maur', key:'Punjab'},
	{value:'Moga', key:'Punjab'},
	{value:'Mohali', key:'Punjab'},
	{value:'Morinda', key:'Punjab'},
	{value:'Mukerian', key:'Punjab'},
	{value:'Muktsar', key:'Punjab'},
	{value:'Nabha', key:'Punjab'},
	{value:'Nakodar', key:'Punjab'},
	{value:'Nangal', key:'Punjab'},
	{value:'Nawanshahr', key:'Punjab'},
	{value:'Pathankot', key:'Punjab'},
	{value:'Patiala', key:'Punjab'},
	{value:'Patran', key:'Punjab'},
	{value:'Patti', key:'Punjab'},
	{value:'Phagwara', key:'Punjab'},
	{value:'Phillaur', key:'Punjab'},
	{value:'Qadian', key:'Punjab'},
	{value:'Raikot', key:'Punjab'},
	{value:'Rajpura', key:'Punjab'},
	{value:'Rampura Phul', key:'Punjab'},
	{value:'Rupnagar', key:'Punjab'},
	{value:'Samana', key:'Punjab'},
	{value:'Sangrur', key:'Punjab'},
	{value:'Sirhind Fatehgarh Sahib', key:'Punjab'},
	{value:'Sujanpur', key:'Punjab'},
	{value:'Sunam', key:'Punjab'},
	{value:'Talwara', key:'Punjab'},
	{value:'Tarn Taran', key:'Punjab'},
	{value:'Urmar Tanda', key:'Punjab'},
	{value:'Zira', key:'Punjab'},
	{value:'Zirakpur', key:'Punjab'},
	{value:'Bali', key:'Rajasthan'},
	{value:'Banswara', key:'Rajastan'},
	{value:'Ajmer', key:'Rajasthan'},
	{value:'Alwar', key:'Rajasthan'},
	{value:'Bandikui', key:'Rajasthan'},
	{value:'Baran', key:'Rajasthan'},
	{value:'Barmer', key:'Rajasthan'},
	{value:'Bikaner', key:'Rajasthan'},
	{value:'Fatehpur', key:'Rajasthan'},
	{value:'Jaipur', key:'Rajasthan'},
	{value:'Jaisalmer', key:'Rajasthan'},
	{value:'Jodhpur', key:'Rajasthan'},
	{value:'Kota', key:'Rajasthan'},
	{value:'Lachhmangarh', key:'Rajasthan'},
	{value:'Ladnu', key:'Rajasthan'},
	{value:'Lakheri', key:'Rajasthan'},
	{value:'Lalsot', key:'Rajasthan'},
	{value:'Losal', key:'Rajasthan'},
	{value:'Makrana', key:'Rajasthan'},
	{value:'Malpura', key:'Rajasthan'},
	{value:'Mandalgarh', key:'Rajasthan'},
	{value:'Mandawa', key:'Rajasthan'},
	{value:'Mangrol', key:'Rajasthan'},
	{value:'Merta value', key:'Rajasthan'},
	{value:'Mount Abu', key:'Rajasthan'},
	{value:'Nadbai', key:'Rajasthan'},
	{value:'Nagar', key:'Rajasthan'},
	{value:'Nagaur', key:'Rajasthan'},
	{value:'Nargund', key:'Rajasthan'},
	{value:'Nasirabad', key:'Rajasthan'},
	{value:'Nathdwara', key:'Rajasthan'},
	{value:'Navalgund', key:'Rajasthan'},
	{value:'Nawalgarh', key:'Rajasthan'},
	{value:'Neem-Ka-Thana', key:'Rajasthan'},
	{value:'Nelamangala', key:'Rajasthan'},
	{value:'Nimbahera', key:'Rajasthan'},
	{value:'Nipani', key:'Rajasthan'},
	{value:'Niwai', key:'Rajasthan'},
	{value:'Nohar', key:'Rajasthan'},
	{value:'Nokha', key:'Rajasthan'},
	{value:'Pali', key:'Rajasthan'},
	{value:'Phalodi', key:'Rajasthan'},
	{value:'Phulera', key:'Rajasthan'},
	{value:'Pilani', key:'Rajasthan'},
	{value:'Pilibanga', key:'Rajasthan'},
	{value:'Pindwara', key:'Rajasthan'},
	{value:'Pipar value', key:'Rajasthan'},
	{value:'Prantij', key:'Rajasthan'},
	{value:'Pratapgarh', key:'Rajasthan'},
	{value:'Raisinghnagar', key:'Rajasthan'},
	{value:'Rajakhera', key:'Rajasthan'},
	{value:'Rajaldesar', key:'Rajasthan'},
	{value:'Rajgarh (Alwar)', key:'Rajasthan'},
	{value:'Rajgarh (Churu', key:'Rajasthan'},
	{value:'Rajsamand', key:'Rajasthan'},
	{value:'Ramganj Mandi', key:'Rajasthan'},
	{value:'Ramngarh', key:'Rajasthan'},
	{value:'Ratangarh', key:'Rajasthan'},
	{value:'Rawatbhata', key:'Rajasthan'},
	{value:'Rawatsar', key:'Rajasthan'},
	{value:'Reengus', key:'Rajasthan'},
	{value:'Sadri', key:'Rajasthan'},
	{value:'Sadulshahar', key:'Rajasthan'},
	{value:'Sagwara', key:'Rajasthan'},
	{value:'Sambhar', key:'Rajasthan'},
	{value:'Sanchore', key:'Rajasthan'},
	{value:'Sangaria', key:'Rajasthan'},
	{value:'Sardarshahar', key:'Rajasthan'},
	{value:'Sawai Madhopur', key:'Rajasthan'},
	{value:'Shahpura', key:'Rajasthan'},
	{value:'Sheoganj', key:'Rajasthan'},
	{value:'Sikar', key:'Rajasthan'},
	{value:'Sirohi', key:'Rajasthan'},
	{value:'Sojat', key:'Rajasthan'},
	{value:'Sri Madhopur', key:'Rajasthan'},
	{value:'Sujangarh', key:'Rajasthan'},
	{value:'Sumerpur', key:'Rajasthan'},
	{value:'Suratgarh', key:'Rajasthan'},
	{value:'Taranagar', key:'Rajasthan'},
	{value:'Todabhim', key:'Rajasthan'},
	{value:'Todaraisingh', key:'Rajasthan'},
	{value:'Tonk', key:'Rajasthan'},
	{value:'Udaipur', key:'Rajasthan'},
	{value:'Udaipurwati', key:'Rajasthan'},
	{value:'Vijainagar', key:'Rajasthan'},
	{value:'Gangtok', key:'Sikkim'},
	{value:'Calcutta', key:'West Bengal'},
	{value:'Arakkonam', key:'Tamil Nadu'},
	{value:'Arcot', key:'Tamil Nadu'},
	{value:'Aruppukkottai', key:'Tamil Nadu'},
	{value:'Bhavani', key:'Tamil Nadu'},
	{value:'Chengalpattu', key:'Tamil Nadu'},
	{value:'Chennai', key:'Tamil Nadu'},
	{value:'Chinna salem', key:'Tamil nadu'},
	{value:'Coimbatore', key:'Tamil Nadu'},
	{value:'Coonoor', key:'Tamil Nadu'},
	{value:'Cuddalore', key:'Tamil Nadu'},
	{value:'Dharmapuri', key:'Tamil Nadu'},
	{value:'Dindigul', key:'Tamil Nadu'},
	{value:'Erode', key:'Tamil Nadu'},
	{value:'Gudalur', key:'Tamil Nadu'},
	{value:'Kanchipuram', key:'Tamil Nadu'},
	{value:'Karaikudi', key:'Tamil Nadu'},
	{value:'Karungal', key:'Tamil Nadu'},
	{value:'Karur', key:'Tamil Nadu'},
	{value:'Kollankodu', key:'Tamil Nadu'},
	{value:'Lalgudi', key:'Tamil Nadu'},
	{value:'Madurai', key:'Tamil Nadu'},
	{value:'Nagapattinam', key:'Tamil Nadu'},
	{value:'Nagercoil', key:'Tamil Nadu'},
	{value:'Namagiripettai', key:'Tamil Nadu'},
	{value:'Namakkal', key:'Tamil Nadu'},
	{value:'Nandivaram-Guduvancheri', key:'Tamil Nadu'},
	{value:'Nanjikottai', key:'Tamil Nadu'},
	{value:'Natham', key:'Tamil Nadu'},
	{value:'Nellikuppam', key:'Tamil Nadu'},
	{value:'Neyveli', key:'Tamil Nadu'},
	{value:'O Valley', key:'Tamil Nadu'},
	{value:'Oddanchatram', key:'Tamil Nadu'},
	{value:'P.N.Patti', key:'Tamil Nadu'},
	{value:'Pacode', key:'Tamil Nadu'},
	{value:'Padmanabhapuram', key:'Tamil Nadu'},
	{value:'Palani', key:'Tamil Nadu'},
	{value:'Palladam', key:'Tamil Nadu'},
	{value:'Pallapatti', key:'Tamil Nadu'},
	{value:'Pallikonda', key:'Tamil Nadu'},
	{value:'Panagudi', key:'Tamil Nadu'},
	{value:'Panruti', key:'Tamil Nadu'},
	{value:'Paramakudi', key:'Tamil Nadu'},
	{value:'Parangipettai', key:'Tamil Nadu'},
	{value:'Pattukkottai', key:'Tamil Nadu'},
	{value:'Perambalur', key:'Tamil Nadu'},
	{value:'Peravurani', key:'Tamil Nadu'},
	{value:'Periyakulam', key:'Tamil Nadu'},
	{value:'Periyasemur', key:'Tamil Nadu'},
	{value:'Pernampattu', key:'Tamil Nadu'},
	{value:'Pollachi', key:'Tamil Nadu'},
	{value:'Polur', key:'Tamil Nadu'},
	{value:'Ponneri', key:'Tamil Nadu'},
	{value:'Pudukkottai', key:'Tamil Nadu'},
	{value:'Pudupattinam', key:'Tamil Nadu'},
	{value:'Puliyankudi', key:'Tamil Nadu'},
	{value:'Punjaipugalur', key:'Tamil Nadu'},
	{value:'Rajapalayam', key:'Tamil Nadu'},
	{value:'Ramanathapuram', key:'Tamil Nadu'},
	{value:'Rameshwaram', key:'Tamil Nadu'},
	{value:'Rasipuram', key:'Tamil Nadu'},
	{value:'Salem', key:'Tamil Nadu'},
	{value:'Sankarankoil', key:'Tamil Nadu'},
	{value:'Sankari', key:'Tamil Nadu'},
	{value:'Sathyamangalam', key:'Tamil Nadu'},
	{value:'Sattur', key:'Tamil Nadu'},
	{value:'Shenkottai', key:'Tamil Nadu'},
	{value:'Sholavandan', key:'Tamil Nadu'},
	{value:'Sholingur', key:'Tamil Nadu'},
	{value:'Sirkali', key:'Tamil Nadu'},
	{value:'Sivaganga', key:'Tamil Nadu'},
	{value:'Sivagiri', key:'Tamil Nadu'},
	{value:'Sivakasi', key:'Tamil Nadu'},
	{value:'Srivilliputhur', key:'Tamil Nadu'},
	{value:'Surandai', key:'Tamil Nadu'},
	{value:'Suriyampalayam', key:'Tamil Nadu'},
	{value:'Tenkasi', key:'Tamil Nadu'},
	{value:'Thammampatti', key:'Tamil Nadu'},
	{value:'Thanjavur', key:'Tamil Nadu'},
	{value:'Tharamangalam', key:'Tamil Nadu'},
	{value:'Tharangambadi', key:'Tamil Nadu'},
	{value:'Theni Allinagaram', key:'Tamil Nadu'},
	{value:'Thirumangalam', key:'Tamil Nadu'},
	{value:'Thirunindravur', key:'Tamil Nadu'},
	{value:'Thiruparappu', key:'Tamil Nadu'},
	{value:'Thirupuvanam', key:'Tamil Nadu'},
	{value:'Thiruthuraipoondi', key:'Tamil Nadu'},
	{value:'Thiruvallur', key:'Tamil Nadu'},
	{value:'Thiruvarur', key:'Tamil Nadu'},
	{value:'Thoothukudi', key:'Tamil Nadu'},
	{value:'Thuraiyur', key:'Tamil Nadu'},
	{value:'Tindivanam', key:'Tamil Nadu'},
	{value:'Tiruchendur', key:'Tamil Nadu'},
	{value:'Tiruchengode', key:'Tamil Nadu'},
	{value:'Tiruchirappalli', key:'Tamil Nadu'},
	{value:'Tirukalukundram', key:'Tamil Nadu'},
	{value:'Tirukkoyilur', key:'Tamil Nadu'},
	{value:'Tirunelveli', key:'Tamil Nadu'},
	{value:'Tirupathur', key:'Tamil Nadu'},
	{value:'Tiruppur', key:'Tamil Nadu'},
	{value:'Tiruttani', key:'Tamil Nadu'},
	{value:'Tiruvannamalai', key:'Tamil Nadu'},
	{value:'Tiruvethipuram', key:'Tamil Nadu'},
	{value:'Tittakudi', key:'Tamil Nadu'},
	{value:'Udhagamandalam', key:'Tamil Nadu'},
	{value:'Udumalaipettai', key:'Tamil Nadu'},
	{value:'Unnamalaikadai', key:'Tamil Nadu'},
	{value:'Usilampatti', key:'Tamil Nadu'},
	{value:'Uthamapalayam', key:'Tamil Nadu'},
	{value:'Uthiramerur', key:'Tamil Nadu'},
	{value:'Vadakkuvalliyur', key:'Tamil Nadu'},
	{value:'Vadalur', key:'Tamil Nadu'},
	{value:'Vadipatti', key:'Tamil Nadu'},
	{value:'Valparai', key:'Tamil Nadu'},
	{value:'Vandavasi', key:'Tamil Nadu'},
	{value:'Vaniyambadi', key:'Tamil Nadu'},
	{value:'Vedaranyam', key:'Tamil Nadu'},
	{value:'Vellakoil', key:'Tamil Nadu'},
	{value:'Vellore', key:'Tamil Nadu'},
	{value:'Vikramasingapuram', key:'Tamil Nadu'},
	{value:'Viluppuram', key:'Tamil Nadu'},
	{value:'Virudhachalam', key:'Tamil Nadu'},
	{value:'Virudhunagar', key:'Tamil Nadu'},
	{value:'Viswanatham', key:'Tamil Nadu'},
	{value:'Agartala', key:'Tripura'},
	{value:'Badharghat', key:'Tripura'},
	{value:'Dharmanagar', key:'Tripura'},
	{value:'Indranagar', key:'Tripura'},
	{value:'Jogendranagar', key:'Tripura'},
	{value:'Kailasahar', key:'Tripura'},
	{value:'Khowai', key:'Tripura'},
	{value:'Pratapgarh', key:'Tripura'},
	{value:'Udaipur', key:'Tripura'},
	{value:'Achhnera', key:'Uttar Pradesh'},
	{value:'Adari', key:'Uttar Pradesh'},
	{value:'Agra', key:'Uttar Pradesh'},
	{value:'Aligarh', key:'Uttar Pradesh'},
	{value:'Allahabad', key:'Uttar Pradesh'},
	{value:'Amroha', key:'Uttar Pradesh'},
	{value:'Azamgarh', key:'Uttar Pradesh'},
	{value:'Bahraich', key:'Uttar Pradesh'},
	{value:'Ballia', key:'Uttar Pradesh'},
	{value:'Balrampur', key:'Uttar Pradesh'},
	{value:'Banda', key:'Uttar Pradesh'},
	{value:'Bareilly', key:'Uttar Pradesh'},
	{value:'Chandausi', key:'Uttar Pradesh'},
	{value:'Dadri', key:'Uttar Pradesh'},
	{value:'Deoria', key:'Uttar Pradesh'},
	{value:'Etawah', key:'Uttar Pradesh'},
	{value:'Fatehabad', key:'Uttar Pradesh'},
	{value:'Fatehpur', key:'Uttar Pradesh'},
	{value:'Greater Noida', key:'Uttar Pradesh'},
	{value:'Hamirpur', key:'Uttar Pradesh'},
	{value:'Hardoi', key:'Uttar Pradesh'},
	{value:'Jajmau', key:'Uttar Pradesh'},
	{value:'Jaunpur', key:'Uttar Pradesh'},
	{value:'Jhansi', key:'Uttar Pradesh'},
	{value:'Kalpi', key:'Uttar Pradesh'},
	{value:'Kanpur', key:'Uttar Pradesh'},
	{value:'Kota', key:'Uttar Pradesh'},
	{value:'Laharpur', key:'Uttar Pradesh'},
	{value:'Lakhimpur', key:'Uttar Pradesh'},
	{value:'Lal Gopalganj Nindaura', key:'Uttar Pradesh'},
	{value:'Lalganj', key:'Uttar Pradesh'},
	{value:'Lalitpur', key:'Uttar Pradesh'},
	{value:'Lar', key:'Uttar Pradesh'},
	{value:'Loni', key:'Uttar Pradesh'},
	{value:'Lucknow', key:'Uttar Pradesh'},
	{value:'Mathura', key:'Uttar Pradesh'},
	{value:'Meerut', key:'Uttar Pradesh'},
	{value:'Modinagar', key:'Uttar Pradesh'},
	{value:'Muradnagar', key:'Uttar Pradesh'},
	{value:'Nagina', key:'Uttar Pradesh'},
	{value:'Najibabad', key:'Uttar Pradesh'},
	{value:'Nakur', key:'Uttar Pradesh'},
	{value:'Nanpara', key:'Uttar Pradesh'},
	{value:'Naraura', key:'Uttar Pradesh'},
	{value:'Naugawan Sadat', key:'Uttar Pradesh'},
	{value:'Nautanwa', key:'Uttar Pradesh'},
	{value:'Nawabganj', key:'Uttar Pradesh'},
	{value:'Nehtaur', key:'Uttar Pradesh'},
	{value:'NOIDA', key:'Uttar Pradesh'},
	{value:'Noorpur', key:'Uttar Pradesh'},
	{value:'Obra', key:'Uttar Pradesh'},
	{value:'Orai', key:'Uttar Pradesh'},
	{value:'Padrauna', key:'Uttar Pradesh'},
	{value:'Palia Kalan', key:'Uttar Pradesh'},
	{value:'Parasi', key:'Uttar Pradesh'},
	{value:'Phulpur', key:'Uttar Pradesh'},
	{value:'Pihani', key:'Uttar Pradesh'},
	{value:'Pilibhit', key:'Uttar Pradesh'},
	{value:'Pilkhuwa', key:'Uttar Pradesh'},
	{value:'Powayan', key:'Uttar Pradesh'},
	{value:'Pukhrayan', key:'Uttar Pradesh'},
	{value:'Puranpur', key:'Uttar Pradesh'},
	{value:'Purquazi', key:'Uttar Pradesh'},
	{value:'Purwa', key:'Uttar Pradesh'},
	{value:'Rae Bareli', key:'Uttar Pradesh'},
	{value:'Rampur', key:'Uttar Pradesh'},
	{value:'Rampur Maniharan', key:'Uttar Pradesh'},
	{value:'Rasra', key:'Uttar Pradesh'},
	{value:'Rath', key:'Uttar Pradesh'},
	{value:'Renukoot', key:'Uttar Pradesh'},
	{value:'Reoti', key:'Uttar Pradesh'},
	{value:'Robertsganj', key:'Uttar Pradesh'},
	{value:'Rudauli', key:'Uttar Pradesh'},
	{value:'Rudrapur', key:'Uttar Pradesh'},
	{value:'Sadabad', key:'Uttar Pradesh'},
	{value:'Safipur', key:'Uttar Pradesh'},
	{value:'Saharanpur', key:'Uttar Pradesh'},
	{value:'Sahaspur', key:'Uttar Pradesh'},
	{value:'Sahaswan', key:'Uttar Pradesh'},
	{value:'Sahawar', key:'Uttar Pradesh'},
	{value:'Sahjanwa', key:'Uttar Pradesh'},
	{value:'Saidpur', key:' Ghazipur'},
	{value:'Sambhal', key:'Uttar Pradesh'},
	{value:'Samdhan', key:'Uttar Pradesh'},
	{value:'Samthar', key:'Uttar Pradesh'},
	{value:'Sandi', key:'Uttar Pradesh'},
	{value:'Sandila', key:'Uttar Pradesh'},
	{value:'Sardhana', key:'Uttar Pradesh'},
	{value:'Seohara', key:'Uttar Pradesh'},
	{value:'Shahabad', key:' Hardoi'},
	{value:'Shahabad', key:' Rampur'},
	{value:'Shahganj', key:'Uttar Pradesh'},
	{value:'Shahjahanpur', key:'Uttar Pradesh'},
	{value:'Shamli', key:'Uttar Pradesh'},
	{value:'Shamsabad', key:' Agra'},
	{value:'Shamsabad', key:' Farrukhabad'},
	{value:'Sherkot', key:'Uttar Pradesh'},
	{value:'Shikarpur', key:' Bulandshahr'},
	{value:'Shikohabad', key:'Uttar Pradesh'},
	{value:'Shishgarh', key:'Uttar Pradesh'},
	{value:'Siana', key:'Uttar Pradesh'},
	{value:'Sikanderpur', key:'Uttar Pradesh'},
	{value:'Sikandra Rao', key:'Uttar Pradesh'},
	{value:'Sikandrabad', key:'Uttar Pradesh'},
	{value:'Sirsaganj', key:'Uttar Pradesh'},
	{value:'Sirsi', key:'Uttar Pradesh'},
	{value:'Sitapur', key:'Uttar Pradesh'},
	{value:'Soron', key:'Uttar Pradesh'},
	{value:'Suar', key:'Uttar Pradesh'},
	{value:'Sultanpur', key:'Uttar Pradesh'},
	{value:'Sumerpur', key:'Uttar Pradesh'},
	{value:'Tanda', key:'Uttar Pradesh'},
	{value:'Tetri Bazar', key:'Uttar Pradesh'},
	{value:'Thakurdwara', key:'Uttar Pradesh'},
	{value:'Thana Bhawan', key:'Uttar Pradesh'},
	{value:'Tilhar', key:'Uttar Pradesh'},
	{value:'Tirwaganj', key:'Uttar Pradesh'},
	{value:'Tulsipur', key:'Uttar Pradesh'},
	{value:'Tundla', key:'Uttar Pradesh'},
	{value:'Unnao', key:'Uttar Pradesh'},
	{value:'Utraula', key:'Uttar Pradesh'},
	{value:'Varanasi', key:'Uttar Pradesh'},
	{value:'Vrindavan', key:'Uttar Pradesh'},
	{value:'Warhapur', key:'Uttar Pradesh'},
	{value:'Zaidpur', key:'Uttar Pradesh'},
	{value:'Zamania', key:'Uttar Pradesh'},
	{value:'Almora', key:'Uttarakhand'},
	{value:'Bazpur', key:'Uttarakhand'},
	{value:'Chamba', key:'Uttarakhand'},
	{value:'Dehradun', key:'Uttarakhand'},
	{value:'Haldwani', key:'Uttarakhand'},
	{value:'Haridwar', key:'Uttarakhand'},
	{value:'Jaspur', key:'Uttarakhand'},
	{value:'Kashipur', key:'Uttarakhand'},
	{value:'kichha', key:'Uttarakhand'},
	{value:'Kotdwara', key:'Uttarakhand'},
	{value:'Manglaur', key:'Uttarakhand'},
	{value:'Mussoorie', key:'Uttarakhand'},
	{value:'Nagla', key:'Uttarakhand'},
	{value:'Nainital', key:'Uttarakhand'},
	{value:'Pauri', key:'Uttarakhand'},
	{value:'Pithoragarh', key:'Uttarakhand'},
	{value:'Ramnagar', key:'Uttarakhand'},
	{value:'Rishikesh', key:'Uttarakhand'},
	{value:'Roorkee', key:'Uttarakhand'},
	{value:'Rudrapur', key:'Uttarakhand'},
	{value:'Sitarganj', key:'Uttarakhand'},
	{value:'Tehri', key:'Uttarakhand'},
	{value:'Muzaffarnagar', key:'Uttar Pradesh'},
	{value:'Adra', key:' Purulia'},
	{value:'Alipurduar', key:'West Bengal'},
	{value:'Arambagh', key:'West Bengal'},
	{value:'Asansol', key:'West Bengal'},
	{value:'Baharampur', key:'West Bengal'},
	{value:'Bally', key:'West Bengal'},
	{value:'Balurghat', key:'West Bengal'},
	{value:'Bankura', key:'West Bengal'},
	{value:'Barakar', key:'West Bengal'},
	{value:'Barasat', key:'West Bengal'},
	{value:'Bardhaman', key:'West Bengal'},
	{value:'Bidhan Nagar', key:'West Bengal'},
	{value:'Chinsura', key:'West Bengal'},
	{value:'Contai', key:'West Bengal'},
	{value:'Cooch Behar', key:'West Bengal'},
	{value:'Darjeeling', key:'West Bengal'},
	{value:'Durgapur', key:'West Bengal'},
	{value:'Haldia', key:'West Bengal'},
	{value:'Howrah', key:'West Bengal'},
	{value:'Islampur', key:'West Bengal'},
	{value:'Jhargram', key:'West Bengal'},
	{value:'Kharagpur', key:'West Bengal'},
	{value:'Kolkata', key:'West Bengal'},
	{value:'Mainaguri', key:'West Bengal'},
	{value:'Mal', key:'West Bengal'},
	{value:'Mathabhanga', key:'West Bengal'},
	{value:'Medinipur', key:'West Bengal'},
	{value:'Memari', key:'West Bengal'},
	{value:'Monoharpur', key:'West Bengal'},
	{value:'Murshidabad', key:'West Bengal'},
	{value:'Nabadwip', key:'West Bengal'},
	{value:'Naihati', key:'West Bengal'},
	{value:'Panchla', key:'West Bengal'},
	{value:'Pandua', key:'West Bengal'},
	{value:'Paschim Punropara', key:'West Bengal'},
	{value:'Purulia', key:'West Bengal'},
	{value:'Raghunathpur', key:'West Bengal'},
	{value:'Raiganj', key:'West Bengal'},
	{value:'Rampurhat', key:'West Bengal'},
	{value:'Ranaghat', key:'West Bengal'},
	{value:'Sainthia', key:'West Bengal'},
	{value:'Santipur', key:'West Bengal'},
	{value:'Siliguri', key:'West Bengal'},
	{value:'Sonamukhi', key:'West Bengal'},
	{value:'Srirampore', key:'West Bengal'},
	{value:'Suri', key:'West Bengal'},
	{value:'Taki', key:'West Bengal'},
	{value:'Tamluk', key:'West Bengal'},
	{value:'Tarakeswar', key:'West Bengal'},
	{value:'Chikmagalur', key:'Karnataka'},
	{value:'Davanagere', key:'Karnataka'},
	{value:'Dharwad', key:'Karnataka'},
	{value:'Gadag', key:'Karnataka'}
];